### ISSUE TITLE
Search dataset name

### ISSUE THREAD

**Issue by AugustT** [ropensci/rnbn#13]
When doing a getOccurrences search you get back the dataset key. It would be nice to have a function which would convert these for you.

This could be done internally using the listdatasets function

**Comment by rossmounce** [comment]
I am encountering this now.

GA001376 = RECORD
GA001372 = National Trust Species Records
GA000091 = Vascular Plants Database

et cetera, would be nice to be able to put names to codes.

**Comment by AugustT** [comment]
In the meantime you can retrieve the lookup table you need with

```r
lookupTable <- rnbn::listDatasets()
```

**Comment by AugustT** [comment]
Given that rnbn will soon be archived this issue will not be addressed :( 
https://github.com/ropensci/rnbn/issues/37
