### ISSUE TITLE
rgdal dependency

### ISSUE THREAD

**Issue by sckott** [ropensci/rnbn#15]
@AugustT how important is it to have `rgdal` as an import in this pkg?  Curious since thinking of using it in `spocc`, but then users have to deal with installing `rgdal`, which isn't easy - if imprt, no big deal. I can't tell how much you use it here. If not that much, perhaps move to `Suggests` and check whether users have installed before using it?

**Comment by AugustT** [comment]
Hi @sckott 

It is used in the conversion of grid references to lat longs. Probably possible to get rid of it if I think about it...

T

**Comment by AugustT** [comment]
rgdal is imported in createWKT.r. It is used to create the WKT from lat and long. Note sure how easy it is to achieve this with out these functions

**Comment by sckott** [comment]
What are you creating WKT from?  spatial objects of some kind?

**Comment by AugustT** [comment]
Here is the code. The lat long is used to create a circular polygon which is then converted into WKT

```r
    p <- SpatialPointsDataFrame(coords = data.frame(lon = longitude, lat = latitude),
                                data.frame(ID = 1),
                                proj4string = CRS("+proj=longlat +ellps=WGS84 +datum=WGS84"))
    stopifnot(length(p) == 1)
    cust <- sprintf("+proj=tmerc +lat_0=%s +lon_0=%s +k=1 +x_0=0 +y_0=0 +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs", 
                    p@coords[[2]], p@coords[[1]])
    projected <- spTransform(p, CRS(cust))
    buffered <- gBuffer(projected, width = radius, byid = TRUE)
    bufferedOrg <- spTransform(buffered, p@proj4string)
    writeWKT(bufferedOrg)
```

**Comment by sckott** [comment]
Ah, so you're making a polygon from a point and a radius from user input.  Yeah, you could use `lawn` which depends on Javascript turf.js, which has ability to do the same thing, but I don't know if you want to do that. You may prefer the current setup.

**Comment by AugustT** [comment]
Given that rnbn will soon be archived this issue will not be addressed :( 
https://github.com/ropensci/rnbn/issues/37
