### ISSUE TITLE
Pass on curl options to http requests?

### ISSUE THREAD

**Issue by sckott** [ropensci/rnbn#16]
@AugustT curious if you'd be up for allowing users to pass in curl options to functions that make http requests to NBN?  e.g, like

```r
foo(config = httr::verbose()) # get verbose curl output
foo(config = httr::progress()) # get curl progress bar

foo <- function(x, ...) {
    GET(url, ...)
}
```

**Comment by AugustT** [comment]
Certainly happy to allow this if there is a need. Is this as simple as adding the `...` in your example?

**Comment by sckott** [comment]
yes, just add `...` as a parameter, and a parameter def. for it. I usually use `@param ... Further named parameters passed on to \code{\link[httr]{GET}}`
