### ISSUE TITLE
use NEWS, git tags, and releases

### ISSUE THREAD

**Issue by sckott** [ropensci/rnbn#23]
hey @AugustT we want all ropensci pkgs to consistently keep track of changes, following https://github.com/ropensci/onboarding/blob/master/packaging_guide.md#-news  
- use a `NEWS` or `NEWS.md` file to keep track of changes with each version released to CRAN
- git tag each CRAN version
- use the [releases tab](https://github.com/ropensci/rnbn/releases) on this repo to include the associated NEWS items for each tag/version

Can you please do the three above items from now on?

**Comment by AugustT** [comment]
Hi Scott, 

Great idea, I'll do this from now on. 

Tom

**Comment by sckott** [comment]
@AugustT any chance you can start doing this? when I put out ropensci news i have no idea what new features/changes/bug fixes, etc, - Same for  your users :)

**Comment by AugustT** [comment]
Okay, I have most of this in place now. However, the tags I have added to my repo don't seem to pull across into this repo? Do you know how to make that work?

**Comment by sckott** [comment]
Looking at your version, you don't have any tags. Am I missing something?

**Comment by AugustT** [comment]
https://github.com/AugustT/rnbn/tags

**Comment by AugustT** [comment]
It seems tag changes behave in a slightly different way to code changes. Perhaps I need to push them directly to this repo?

**Comment by AugustT** [comment]
Got it! PR does note pull tags. I needed to do

```
git push upstream --tags
```

**Comment by sckott** [comment]
oh, i was looking at https://github.com/JNCC-UK/rnbn since this repo says its forked from there 

nice, i see you got it

**Comment by AugustT** [comment]
Right, I think this is all in place... have I avoided getting coal for Christmas? ;) Let me know if there is anything I have missed.

**Comment by sckott** [comment]
i think it's good now. whenever I see a new version of an ropensci package, I look in https://github.com/ropensci/rnbn/releases for what has changed, so this is very helpful
