### ISSUE TITLE
Sporadic Timeouts

### ISSUE THREAD

**Issue by rossmounce** [ropensci/rnbn#28]
Probably not an issue with this R package but perhaps https://data.nbn.org.uk/ itself,

I'd just like to report I'm getting a lot of Timeout errors when trying to _getOccurrences_ today. Is it just a bad day for the internet? I'm on a UK JANET wired connection so there really shouldn't be any problems with speed my end.

Example:

```
occa <- getOccurrences(tvks = 'NBNSYS0000002010', acceptTandC = TRUE)
Requesting batch 1 of 1 
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
```

Very occasionally it has worked and _not_ given a Timeout error. But 99/100 it hasn't today so I'm not getting much work done...

**Comment by AugustT** [comment]
@rossmounce thanks for getting in touch. This looks like an issue with the NBN gateway, which does occasionally experience problems. The best way to test this is to go to the URL you posted, for me this is currently painfully slow so suspect that is the issue. Unfortunately there is not a server status API, else I would have built a feature which gave a more informative error message.

**Comment by rossmounce** [comment]
@AugustT thanks for the confirmation of what I suspected. Slightly worried about this in the short-term, I have plans to query ~2760 NBN taxon codes soon for a project (once I have all my permissions dealt with, 377 requests still pending!). 

Will the API be smoothly functioning say next week?

**Comment by rossmounce** [comment]
I've heard NBN is moving platforms & harmonising data licensing at the moment so it's probably a bad time to do research with it, but I can't wait. My current funding runs out end of February 2017 so I can't just shelve this and come back when the dust has settled. Sorry!

**Comment by AugustT** [comment]
@rossmounce You're correct that there are some changes going on with the gateway but these should not be effecting your work. I only maintain `rnbn` I don't work on the gateway directly. When I have issues I usually email support@nbn.org.uk and they get back to me within a day. In my experience these sorts of issues only last for a day.

I take it you are trying to get all the NBN data for a large range of taxa? If you continue to have problems I would be happy to discuss further. At the Biological Records Centre we hold lots of data from schemes and societies which forms the majority of data on the NBN outside birds and marine.

**Comment by rossmounce** [comment]
@AugustT thanks that's very reassuring. I am new to using NBN and slightly panicky about it, particularly the permissions/access restrictions - a lot more complex than GBIF! I will try and email NBN directly in future but thanks for the offer of help +1
