### ISSUE TITLE
ERROR: Datum present in data for which parameters have not been given (‘NA’)

### ISSUE THREAD

**Issue by rossmounce** [ropensci/rnbn#29]
I keep bumping into this error message which appears to prevent me from downloading any records associated with the taxon. A fairly frequent error too...

Example:

```
data <- getOccurrences(tvks = 'NBNSYS0000002045', acceptTandC = TRUE)
Error in OSGridstoLatLong(org_en$EASTING, org_en$NORTHING, org_en$PROJECTION) : 
  ERROR: Datum present in data for which parameters have not been given (‘NA’)
```

Notes:

```
> packageVersion("rnbn")
[1] ‘1.0.3’
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.1 LTS

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8       
 [4] LC_COLLATE=en_GB.UTF-8     LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] httr_1.2.1   rnbn_1.0.3   plyr_1.8.4   rnrfa_1.2    rJava_0.9-8  rgeos_0.3-21
[7] rgdal_1.1-10 raster_2.5-8 sp_1.2-3    

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.7       xml2_1.0.0        magrittr_1.5      maps_3.1.1       
 [5] munsell_0.4.3     cowplot_0.7.0     colorspace_1.2-7  geosphere_1.5-5  
 [9] lattice_0.20-34   R6_2.2.0          rjson_0.2.15      jpeg_0.1-8       
[13] stringr_1.1.0     xts_0.9-7         tools_3.3.2       parallel_3.3.2   
[17] grid_3.3.2        gtable_0.2.0      png_0.1-7         ggmap_2.6.1      
[21] mapproj_1.2-4     reshape2_1.4.2    ggplot2_2.1.0     curl_2.2         
[25] stringi_1.1.2     RgoogleMaps_1.4.1 scales_0.4.0      jsonlite_1.1     
[29] zoo_1.7-13        proto_1.0.0 

```

Other NBN codes so far which give the same error message:

NBNSYS0000002016
NBNSYS0000002018
NBNSYS0000002022
NBNSYS0000002025
NBNSYS0000002027
NBNSYS0000002036
NBNSYS0000002039
NBNSYS0000002046
NBNSYS0000002050

**Comment by rossmounce** [comment]
okay...

having RTFM there appears to be a temporary workaround if latlongs are not needed but I guess it's still a valid issue(?)

```
data <- getOccurrences(tvks = 'NBNSYS0000002045', acceptTandC = TRUE, latLong = F)
dim(data)
[1] 3452   23
```

**Comment by AugustT** [comment]
This is a valid issue. I acutally came across this in some code yesterday but hadn't clicked that it would be an issue in rnbn. This happens when the grid reference in the data is NA. Why this data would be useful I dont know. Anytway, if it is NA then the code that converts gridref to lat long freaks out. I will change this so teat NA in gives NA out.

**Comment by AugustT** [comment]
If you are working on this over hte weekend I have a quick fix on my fork (untested but should be good)

https://github.com/ropensci/rnbn/pull/27/commits/e4f5af7290249490cd520ea01733957cd5119614

**Comment by rossmounce** [comment]
Just to clarify: I think it's not quite just cases where 'location' == NA

In the case of the NBNSYS0000002045 records I am allowed access, with latLong=F (a bit of a stymie on reproducibility...) none of the records have NA as the 'location' (grid reference), however there are 7 records whose 'resolution' is "Polygon" and in the 'location' is a text string like "POLRUAN TO POLPERRO" 

Hopefully I'll be playing with my baby daughter all this weekend rather than R'ing but you never know... :o)

**Comment by AugustT** [comment]
Hmm, looks like this might need more digging. Can you paste in the grid references in here for one that failed... something must be up with them.

Off for a pint now! Back to this on Monday

**Comment by AugustT** [comment]
Yeah, ` "POLRUAN TO POLPERRO / 1 : 14-09-2012. Feature F0060"` is definatly not a grid reference! Working on a fix

**Comment by AugustT** [comment]
This should now be fixed. I ran the follow with no errors

```r
rm(list = ls())

library(rnbn)
nbnLogin(username = '****', password = '****')

tvks <- c('NBNSYS0000002016','NBNSYS0000002018',
          'NBNSYS0000002022','NBNSYS0000002025',
          'NBNSYS0000002027','NBNSYS0000002036',
          'NBNSYS0000002039','NBNSYS0000002046',
          'NBNSYS0000002050')

for(i in tvks){
    
    data_LL <- getOccurrences(tvks = i,
                              acceptTandC = TRUE,
                              latLong = TRUE)
}
```
