### ISSUE TITLE
SSL certificates

### ISSUE THREAD

**Issue by sckott** [ropensci/rnbn#3]
We were at a hackathon recently, and the DataONE folks use SSL certificates as well for authentication. @mbjones realized that the default curl version on Mavericks (and maybe other OSX versions?) doesn't work, but does if you update to a more recent curl version. Not sure if there are problems on other OS'es

**Comment by AugustT** [comment]
Given that rnbn will soon be archived this issue will not be addressed :( 
https://github.com/ropensci/rnbn/issues/37
