### ISSUE TITLE
Inconsistent field numbering (order) of record fields between searches

### ISSUE THREAD

**Issue by rossmounce** [ropensci/rnbn#30]
When I do a tvk search e.g.

```
occe <- getOccurrences(tvks = 'NBNSYS0000003088', acceptTandC = TRUE, latLong=F)
```

When "latLong=F" I usually get data back that has 24 fields in a consistent order e.g.

```
#in bash shell with csvkit https://csvkit.readthedocs.io/en/0.9.1/
csvcut -n NHMSYS0000840690.csv 
  1: 
  2: observationID
  3: fullVersion
  4: datasetKey
  5: surveyKey
  6: sampleKey
  7: observationKey
  8: siteKey
  9: siteName
 10: featureID
 11: location
 12: resolution
 13: taxonVersionKey
 14: pTaxonVersionKey
 15: pTaxonName
 16: pTaxonAuthority
 17: startDate
 18: endDate
 19: sensitive
 20: absence
 21: publicAttribute
 22: dateTypekey
 23: recorder
 24: determiner
```

However, in an isolated number of cases I have seen anything from 19 to 23 fields of information returned in the csv (examples further below). Can I ask that even if a field is blank/null/not given in all matching records, that the field is still returned in the output/downloaded csv file for consistencies sake? I'm lazy scripter so I sometimes rely on field order/numbering to be consistent across files...

A 19 field example (the taxon is sensu lato so I understand why it might not have taxon authority information),   :

```
occe <- getOccurrences(tvks = 'NHMSYS0021118903', acceptTandC = TRUE, latLong=F)
write.csv(occe,file="NHMSYS0021118903.csv")
#in bash shell using csvkit 
csvcut -n NHMSYS0021118903.csv 
  1: 
  2: observationID
  3: fullVersion
  4: datasetKey
  5: surveyKey
  6: sampleKey
  7: observationKey
  8: featureID
  9: location
 10: resolution
 11: taxonVersionKey
 12: pTaxonVersionKey
 13: pTaxonName
 14: startDate
 15: endDate
 16: sensitive
 17: absence
 18: publicAttribute
 19: dateTypekey
```

A 20 field example  :

```
occe <- getOccurrences(tvks = 'NHMSYS0000459471', acceptTandC = TRUE, latLong=F)
write.csv(occe,file="NHMSYS0000459471.csv")
#in bash shell using csvkit https://csvkit.readthedocs.io/en/0.9.1/
csvcut -n NHMSYS0000459471.csv 
  1: 
  2: observationID
  3: fullVersion
  4: datasetKey
  5: surveyKey
  6: sampleKey
  7: observationKey
  8: featureID
  9: location
 10: resolution
 11: taxonVersionKey
 12: pTaxonVersionKey
 13: pTaxonName
 14: pTaxonAuthority
 15: startDate
 16: endDate
 17: sensitive
 18: absence
 19: publicAttribute
 20: dateTypekey
```

A 21 field example:

```
csvcut -n NBNSYS0100002210.csv 
  1: 
  2: observationID
  3: fullVersion
  4: datasetKey
  5: surveyKey
  6: sampleKey
  7: observationKey
  8: featureID
  9: location
 10: resolution
 11: taxonVersionKey
 12: pTaxonVersionKey
 13: pTaxonName
 14: startDate
 15: endDate
 16: sensitive
 17: absence
 18: publicAttribute
 19: dateTypekey
 20: siteKey
 21: siteName

```

A 22-field example:

```
csvcut -n NBNSYS0000002044.csv 
  1: 
  2: observationID
  3: fullVersion
  4: datasetKey
  5: surveyKey
  6: sampleKey
  7: observationKey
  8: siteKey
  9: siteName
 10: featureID
 11: location
 12: resolution
 13: taxonVersionKey
 14: pTaxonVersionKey
 15: pTaxonName
 16: pTaxonAuthority
 17: startDate
 18: endDate
 19: sensitive
 20: absence
 21: publicAttribute
 22: dateTypekey

```

A 23-field example:

```
csvcut -n NBNSYS0100005722.csv 
  1: 
  2: observationID
  3: fullVersion
  4: datasetKey
  5: surveyKey
  6: sampleKey
  7: observationKey
  8: featureID
  9: location
 10: resolution
 11: taxonVersionKey
 12: pTaxonVersionKey
 13: pTaxonName
 14: startDate
 15: endDate
 16: sensitive
 17: absence
 18: publicAttribute
 19: dateTypekey
 20: siteKey
 21: siteName
 22: determiner
 23: recorder

```

**Comment by AugustT** [comment]
"I sometimes rely on field order/numbering to be consistent across files"

I guess the annoying answer is to say that this is a bad idea. What is the actual problem that you have? Are you trying to rbind tables and having problems? Are you trying to look up values in columns that are not present? It might be easier for you to change your script than for me to change rnbn. I am also keen to keep the rnbn output as true to the APIs as possible so that if columns are added/changed these are accurately reflected in rnbn

**Comment by rossmounce** [comment]
Some context...

I know I can use getOccurrences() with multiple tvks but since I have ~2700 tvks I search each tvk on its own with getOccurrences() and output these to a .csv file. I get back about 29 million records across those ~2700 tvks (scale is important here, need to use computationally fast methods).

I transform all the .csv's to remove quoted commas, to make my life easier, ensuring that all commas in each file are only used as field delimiters.

```
sed -i ':a;s/^\(\([^"]*,\?\|"[^",]*",\?\)*"[^",]*\),/\1 /;ta' *.csv
```

I would like to query across all these output .csv files to say determine how many non-public records were returned across all ~2700 tvk searches. If the data were consistently output I could do:

```
cut -d, -f21 *.csv | sort | uniq -c | sort -nr | head
24520392 "FALSE"
1634715 "TRUE"
1168190 NA
 187733 "D"
 182706 "YY"
 110652 "D "
  91022 "Y "
  66372 "Y"
  23970 "DD"
  16346 "Site name unavailable"
```

there should only be TRUE or FALSE in that field however, because of the inconsistencies I'm getting a lot of pollution from other fields e.g. "Site name unavailable"

csvkit can call fields by name rather than number but it can't do this across more than one file unlike `cut` unfortunately

```
csvcut -c publicAttribute NHMSYS0100003189.csv | sort | uniq -c | sort -nr ;
     55 FALSE
      9 TRUE
      1 publicAttribute

```

I'd prefer to keep with shell solutions for speed & efficiency rather than R basically.

I know this is a 'nice to have' request rather than super-necessary but I do think _ideally_ we should have standard, reliable output, between queries, right?

**Comment by rossmounce** [comment]
PS I don't expect you to write workaround scripts, I'll figure it out for myself. Just filing issues because I like filing issues :smiley:

**Comment by AugustT** [comment]
Why not do it in your R script when you retrieve the data? Would be better than having to have an extra shell script?

```r
data <- getOccurrences(...)

#how many rows
nrows(data)

# how many public
sum(data$publicAttribute)
```

Also this is a parallel problem, but I guess you already know that from your twitter post.

As a side note, if you were to parallelise this you could cause the NBN servers some serious problems (effectively a DNS attack), as the hardware is not super good. So you might want to drop them an email.

**Comment by AugustT** [comment]
disclosure - the console scares me

**Comment by rossmounce** [comment]
Ah... okay, I have a viable workaround! 

I'll just use Miller (mlr) in the meantime, it can use field names
http://johnkerl.org/miller/doc/
https://github.com/johnkerl/miller

**Comment by rossmounce** [comment]
The files need additional prep to make them 'Miller-compliant' but I am happy!

```
#Remove quoted commas
gawk -i inplace -F'"' -v OFS='' '{ for (i=2; i<=NF; i+=2) gsub(",", "", $i) } 1'
#mlr doesn't like un-named csv fields, so add A as the name for the first field
sed -i '1s/^/A/' *.csv
#remove double quotes in header row
sed -i 's/"//g' *.csv
# one can now use Miller to analyze across csvs using the field name, even if the fields are in different positions between files
mlr --csv --rs lf cut -f publicAttribute *.csv | sort | uniq -c | sort -nr
1164445 FALSE
 116377 TRUE
      1 publicAttribute

```
