### ISSUE TITLE
Report what % of records user has access to [enhancement]

### ISSUE THREAD

**Issue by rossmounce** [ropensci/rnbn#33]
Given the complicated nature of access permissions to data (split across sometimes very many different datasets), it would be nice to report for each tvk search what % of _total_ NBN records one can/has retrieved with getOccurrences()

e.g. currently when I retrieve records for NBNSYS0000002718 (Ranunculus flammula L.), I only get 68102 records returned, yet the NBN Gateway search webpage for the tvk (https://data.nbn.org.uk/Search?q=Ranunculus+flammula) seems to indicate there are 73504 records available for this taxon.

Presumably the difference is the datasets I do not have "better/enhanced access" permission for?

I would like it reported (somehow, via rnbn) that my download of 68102 records was only 92% of the available records associated with that tvk.

another e.g. _Eriophorum angustifolium_ NBNSYS0000002372
I can download 43937 (97%) records but the GUI websearch seems to indicate that there are 45302 for this taxon.

I'm sure you can appreciate the importance of knowing what proportion of the total records a researcher has access to. (Ideally it would always be 100% but that's not the issue I'm raising here)

**Comment by AugustT** [comment]
This is a feature I have rifted on before. I think it would be useful to know these number too but often people are not downloading all the data for a species as you are. Say I was downloading data for Ranunculus flammula for Oxfordshire, I would want to know how many records I was missing for Oxfordshire. Or if I was getting records for all species from a 10km grid square I would like to know how many records I was missing from that grid square. These are more complex instances of your problem. 

To be honest I have little time to work on this and with the move to the atlas of living Australia architecture coming up there is little value in spending time on this now.

**Comment by rossmounce** [comment]
Fair enough. 

I look forward to the new architecture and hopefully a better culture of openness to come with it...(?)

**Comment by AugustT** [comment]
see page 10+ https://nbn.org.uk/wp-content/uploads/2016/01/NBN_Action_Plan_final.pdf

**Comment by AugustT** [comment]
Given that rnbn will soon be archived this issue will not be addressed :( 
https://github.com/ropensci/rnbn/issues/37
